apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd-image-updater.argoproj.io/image-list: 'testing=docker.io/redheaven/my-nginx-image:demo'
    argocd-image-updater.argoproj.io/testing.update-strategy: 'digest' #There are several ways to update the image, but I'm using digest
    argocd-image-updater.argoproj.io/git-branch: 'master'
    argocd-image-updater.argoproj.io/testing.force-update: 'true'
    argocd-image-updater.argoproj.io/write-back-method: 'git:secret:argocd/git-creds'
  name: argocd-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/irfanrizkiantopratama/argocd-test.git
    targetRevision: HEAD
    path: k8s/nginx
  sources: []
  destination: 
    server: https://kubernetes.default.svc
    namespace: my-app
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
